### ISSUE TITLE
Traceback errors after latest updates

### ISSUE THREAD

**Issue by jcadig1** [rynecarbone/power_ranker#2]
Getting traceback errors now after the latest update, please see the attached output file, seems it has to do with the LSQ changes?

`Traceback (most recent call last):
  File "/usr/local/bin/power_ranker", line 11, in <module>
    load_entry_point('power-ranker==1.1.1', 'console_scripts', 'power_ranker')()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jcadig1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/power_ranker-1.1.1-py3.6.egg/scripts/command_line.py", line 9, in <module>
    from power_ranker.league import League
  File "/usr/local/lib/python3.6/dist-packages/power_ranker-1.1.1-py3.6.egg/power_ranker/league.py", line 17, in <module>
    from .lsq import LSQ
ImportError: cannot import name 'LSQ'
`

**Comment by rynecarbone** [comment]
Yes, the most recent commits on github aren't functional quite yet. The last release was still working until ESPN updated their API so I'm going through the code now to update everything with the new API.   I've currently implemented code to hit the new endpoints, get season data, and calculate rankings for colley, lsq, and two step dominance. The rest I hope to get done by week 2 or latest week 3. 

It's a little more involved than just changing the endpoints since the structure of the data is also completely different. Since I have to deal with new data anyway, I'm also updating the structure of the code so that it uses pandas and vectorizes all the operations.

**Comment by rynecarbone** [comment]
The most recent commit (1b0a4e7949218ab9667bbea5b61392ccb416b8bc) should now run without breaking. 

The only things not functional yet are: 
 1) League History page
 2) Playoff simulation

The scraping, calculations, plotting, and website generation (with the exception of the history page) are working.

**Comment by jcadig1** [comment]
Is this currently functional for you? 

I am still having issues after updating. I'm using WSL, think that has anything to do with it? Don't think it should...


`Using MY_LOCAL_CONFIG.cfg to generate power rankings
Traceback (most recent call last):
  File "/usr/local/bin/power_ranker", line 11, in <module>
    load_entry_point('power-ranker==1.1.1', 'console_scripts', 'power_ranker')()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/scripts/command_line.py", line 90, in main
    run_cl_rankings(args.config, private_league=args.private)
  File "/home/jcadig1/.local/lib/python3.6/site-packages/scripts/command_line.py", line 20, in run_cl_rankings
    my_league = League(config_file)
  File "/home/jcadig1/.local/lib/python3.6/site-packages/power_ranker/league.py", line 38, in __init__
    self._scrape_league()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/power_ranker/league.py", line 57, in _scrape_league
    data = r.json()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 2 (char 2)
`
