### ISSUE TITLE
Still getting errors

### ISSUE THREAD

**Issue by jcadig1** [rynecarbone/power_ranker#3]
Is this currently functional for you? If so, what are you running this on?

I am still having issues after updating to 1b0a4e7:

`Using MY_LOCAL_CONFIG.cfg to generate power rankings
Traceback (most recent call last):
  File "/usr/local/bin/power_ranker", line 11, in <module>
    load_entry_point('power-ranker==1.1.1', 'console_scripts', 'power_ranker')()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/scripts/command_line.py", line 90, in main
    run_cl_rankings(args.config, private_league=args.private)
  File "/home/jcadig1/.local/lib/python3.6/site-packages/scripts/command_line.py", line 20, in run_cl_rankings
    my_league = League(config_file)
  File "/home/jcadig1/.local/lib/python3.6/site-packages/power_ranker/league.py", line 38, in __init__
    self._scrape_league()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/power_ranker/league.py", line 57, in _scrape_league
    data = r.json()
  File "/home/jcadig1/.local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 2 (char 2)
`

_Originally posted by @jcadig1 in https://github.com/rynecarbone/power_ranker/issues/2#issuecomment-529988987_

**Comment by rynecarbone** [comment]
Have you tried re-running  'python3 setup.py install'? I'm running windows 10 and installing into a fresh python virtual environment works for me both with git-bash and in ubuntu/windows subsystem for linux (WSL).

The error looks like the error that was being generated when espn changed the api endpoint and the response was empty so it looks like you may have updated your code to the newest commit but not actually installed the updates to the executable?

**Comment by jcadig1** [comment]
I've been using ubuntu on WSL as well. Maybe a prerequisite I'm missing? I've been pulling straight from the git page and installing using python3. Only error it's thrown was for a scipy version but I upgraded scipy and that was no longer an issue. I'll try a fresh install of ubuntu WSL and see....

**Comment by jcadig1** [comment]
Yea, not sure why but a clean install and upgrade to 19.04 did the trick.

**Comment by rynecarbone** [comment]
Great, glad it's working! I'm about to push the league history update and release a new version on pip so keep an eye out for that and let me know if there are any more issues
